version: 2.1
jobs:
  Builder:
   docker:
      - image: dopaemon/bionic:latest
   steps:
      - add_ssh_keys:
          fingerprints:
            - "1d:06:03:42:fb:f1:35:4b:ca:85:dd:5c:d9:80:a2:ff"
      - run:
          name: Config
          no_output_timeout: 10m
          command: |
            git config --global user.name "dopaemon"
            git config --global user.email "polarisdp@gmail.com"
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          name: Git Clone Repo
          no_output_timeout: 5m
          command: |
            git clone git@github.com:KernelPanic-OpenSource/KernelPanic-OpenSource.github.io.git ~/Repo
      - run:
          name: Remove
          no_output_timeout: 5m
          command: |
            cd ~/Repo
            rm -rvf Packages.bz2
            git rm Packages.bz2
            git add -v -A
            git commit -sm "Remove Old Packages"
      - run:
          name: GitPush
          no_output_timeout: 5m
          command: |
            cd ~/Repo
            echo "yes" | git push -f origin master
      - run:
          name: Building
          no_output_timeout: 5m
          command: |
            cd ~/Repo
            bzip2 -zvk Packages
            git add -v -A
            git commit -sm "Add New Packages"
      - run:
          name: GitPush
          no_output_timeout: 5m
          command: |
            cd ~/Repo
            echo "yes" | git push -f origin master            
workflows:
  version: 2.1
  cooking:
    jobs:
      - Builder
